name: telegram-bot
services:
  - name: telegram-bot
    docker:
      image: python:3.13.7
      command: ["python", "bot.py"]
    ports:
      - port: 3000
        http_path: /health
    env:
      - name: PYTHONUNBUFFERED
        value: "1"
    health_checks:
      http:
        path: /health
        port: 3000
        interval: 30
        timeout: 3
